### ISSUE TITLE
Run vm on a real platform

### ISSUE THREAD

**Issue by JingHanZhan** [seL4/camkes-vm-examples#1]
Hi,

I try to follow the documentation to build.
And it generate two image **capdl-loader-image-x86_64-pc99**  and **kernel-x86_64-pc99**. 
What is different between  them ?
And how can I use them to run on a real platform ?

 Thanks !

**Comment by walle-whale** [comment]
Hi JingHanZan, can you please ask your question on the mailing list.
https://sel4.systems/lists/listinfo
