### ISSUE TITLE
This uses SEL4PROJ/linux-tegra, which has not been migrated to the sel4 Foundation space

### ISSUE THREAD

**Issue by axel-h** [seL4/camkes-vm-examples#17]
This uses the repo https://github.com/SEL4PROJ/linux-tegra, which has not been migrated to https://github.com/sel4 yet. Are there any license issues preventing this or is this just another open maintenance task?

**Comment by lsf37** [comment]
Not sure it should be migrated here, it's for an old platform and essentially unmaintained at the moment. There are no license issues I'm aware of if we wanted to move it, though.

**Comment by lsf37** [comment]
Will close this as there is no plan for further development of that image. If it becomes relevant again, fee free to reopen.
