### ISSUE TITLE
For VM_ Multi, how can I interact with different virtual machines?

### ISSUE THREAD

**Issue by Comet959** [seL4/camkes-vm-examples#22]
Hi,
I read the doc https://github.com/seL4/camkes-vm under Serial, know that i can use `@m` to control vm，but i don't know where to send `@m`, and how to send it. 

I just want to **switch the command shell** between two vms on my board which started the app vm_multi.

How can i fix it ?

**Comment by wom-bat** [comment]
Do what it says.  On the serial console, you'll see different VMs give different coloured output.
At the beginning of a line, type `@1` to connect the input to VM 1; `@2` to connect to the 2nd VM and so on.
