### ISSUE TITLE
Camkes-VM-Linux Ninja couldn't build file

### ISSUE THREAD

**Issue by sriram-2** [seL4/camkes-vm-examples#26]
I am a newbie to SeL4 and followed the step by step process to build camkes-vm-linux project
but it fails while running ninja and the output is as follows
```
ubuntu@ubuntu1804:~/sel4-tutorials-manifest/b11_build$ ninja
[5/427] Performing configure step for 'hello-app'
FAILED: hello-app-stamp/hello-app-configure 
cd /home/ubuntu/sel4-tutorials-manifest/b11_build/hello-app && /usr/local/bin/cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN_FILE=/home/ubuntu/sel4-tutorials-manifest/tools/seL4/cmake-tool/polly_toolchains/linux-gcc-32bit-pic.cmake -GNinja /home/ubuntu/sel4-tutorials-manifest/b11/pkg/hello && /usr/local/bin/cmake -E touch /home/ubuntu/sel4-tutorials-manifest/b11_build/hello-app-stamp/hello-app-configure
-- [polly] Used toolchain: Linux / gcc / PIC / c++11 support / 32 bit
-- The C compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/gcc
-- Check for working C compiler: /usr/bin/gcc -- broken
CMake Error at /usr/local/share/cmake-3.13/Modules/CMakeTestCCompiler.cmake:52 (message):
  The C compiler
    "/usr/bin/gcc"
  is not able to compile a simple test program.
  It fails with the following output:
    Change Dir: /home/ubuntu/sel4-tutorials-manifest/b11_build/hello-app/CMakeFiles/CMakeTmp
    
    Run Build Command:"/usr/bin/ninja-build" "cmTC_ac0a4"
    [1/2] Building C object CMakeFiles/cmTC_ac0a4.dir/testCCompiler.c.o
    [2/2] Linking C executable cmTC_ac0a4
    FAILED: cmTC_ac0a4 
    : && /usr/bin/gcc -m32 -fPIC   CMakeFiles/cmTC_ac0a4.dir/testCCompiler.c.o  -o cmTC_ac0a4   && :
    /usr/bin/ld: cannot find Scrt1.o: No such file or directory
    /usr/bin/ld: cannot find crti.o: No such file or directory
    /usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/7/libgcc.a when searching for -lgcc
    /usr/bin/ld: cannot find -lgcc
    /usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/7/libgcc.a when searching for -lgcc
    /usr/bin/ld: cannot find -lgcc
    collect2: error: ld returned 1 exit status
    ninja: build stopped: subcommand failed.

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:5 (project)

-- Configuring incomplete, errors occurred!
See also "/home/ubuntu/sel4-tutorials-manifest/b11_build/hello-app/CMakeFiles/CMakeOutput.log".
See also "/home/ubuntu/sel4-tutorials-manifest/b11_build/hello-app/CMakeFiles/CMakeError.log".
```
What changes are to be made and How do I solve this.

**Comment by Ivan-Velickovic** [comment]
I'm not sure exactly what the issue with your version of GCC is but you will need at least GCC version 8 for seL4 projects, you can find the instructions for acquiring it on Ubuntu 18.04 here: https://docs.sel4.systems/projects/buildsystem/host-dependencies.html.

**Comment by sriram-2** [comment]
the version is 8.4.0 , is it fine or do i need to update or are there changes to be made somewhere else

**Comment by Ivan-Velickovic** [comment]
The output has "The C compiler identification is GNU 7.5.0", it seems that it's not finding that version of GCC. You might need to run the `update-alternatives` command listed on the dependencies page.

**Comment by kent-mcleod** [comment]
The issue here is likely due to the host machine not having the 32-bit Linux standard libraries installed. The x86 VM uses a 32-bit guest Linux. In order to build a test program to run inside the guest, the host machine needs to have the build dependencies installed for building a 32-bit Linux binary.
The camkes docker containers should have these dependencies installed correctly.  The relevant dpkg/apt installation commands are here:
https://github.com/seL4/seL4-CAmkES-L4v-dockerfiles/blob/master/scripts/camkes.sh#L36-L46:
```
# Get dependencies
as_root dpkg --add-architecture i386
as_root apt-get update -q
as_root apt-get install -y --no-install-recommends \
    acl \
    fakeroot \
    linux-libc-dev-i386-cross \
    linux-libc-dev:i386 \
    pkg-config \
    spin \
    lib32stdc++-10-dev
```

**Comment by axel-h** [comment]
@sriram-2: did this solve your problem, so we can clsoe this?

**Comment by sriram-2** [comment]
@axel-h yes it did, Thanks!
But im unable to input while running it and getting this as serial output
Any help would be great
Serial Output
"""

Starting network[    0.810972] ip (679) used greatest stack depth: 6732 bytes left
: OK

Failed to locate device consumes_event.
Failed to locate device emits_event.

Welcome to Buildroot

buildroot login: [    1.431752] clocksource: tsc: mask: 0xffffffffffffffff max_cycles: 0x31015f85297, max_idle_ns: 440795334135 ns

[    1.442241] clocksource: Switched to clocksource tsc

[    2.811817] random: fast init done

[  134.023597] random: crng init done

""""

**Comment by kent-mcleod** [comment]
What hardware platform is being used or is this on a simulator?

**Comment by axel-h** [comment]
closing this because there has been no response.
