### ISSUE TITLE
vm_introspect is broken, not visible because CI does not cover it

### ISSUE THREAD

**Issue by axel-h** [seL4/camkes-vm-examples#38]
CI does not cover `apps/Arm/vm_introspect`, see https://github.com/seL4/ci-actions/blob/master/camkes-vm/builds.yml with the current coverage. At least a build for all examples should happen.

**Comment by lsf37** [comment]
Yes, that would be nice to extend. Happy to help if someone would like to make a start.

I'm not sure I added support for build-only, but that could probably be achieved relatively easily.

**Comment by axel-h** [comment]
https://github.com/seL4/camkes-vm/pull/122 is a test for adding this to CI, it shows that vm_introspect is broken.
