### ISSUE TITLE
VM_minimal for QEMU/ARMv7 does not work due to missing linux images

### ISSUE THREAD

**Issue by axel-h** [seL4/camkes-vm-examples#73]
I've been testing some more CI configurations and ran into some issues with QEMU/ARMv7 CMake that prevent this from working nicely. Once these are resolved, building `VM_minimal` for QEMU/ARMv7 works, but it still misses a 32-bit linux image. There should at least be a warning in CMake scripts that this is unsupported. I'm not sure if this platform has worked once and just needs the linux images, or if there more that needs to be done. There seems not much practical value in ARMv7 virtualization nowadays.

**Comment by lsf37** [comment]
I think it's fine to declare qemu for armv7a unsupported. It was never supported in the first place, and virtualisation work is all focussing on 64 bit currently.
